services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    ports:
      - "8000:8000" # Splunk Web interface
      - "8088:8088" # HTTP Event Collector
      - "9997:9997" # Forwarding port
      - "8089:8089" # Rest API

    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=yourpassword
    volumes:
      - splunk-data:/opt/splunk/var
    restart: unless-stopped

volumes:
  splunk-data:
